name: Go
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1.0.0
      with:
        go-version: 1.13

    - name: Build
      run: go build . -o GoMicroCli-${{ matrix.platform }}
    
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        files: GoMicroCli-${{ matrix.platform }}
