name: ci

on:
  pull_request:
    branches:
      - master
      - releases/*
  push:
    branches:
      - master
      - releases/*

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - v0.117.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
        name: GoReleaser
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: release --skip-publish --rm-dist
